export function generateISOReport(project: any) {
  const today = new Date().toLocaleDateString()

  return `
PROCESS ANALYSIS REPORT
Generated by Vesimy

--------------------------------------------------
Document Control
--------------------------------------------------
Document ID: VSM-${project.id}
Revision: 1.0
Prepared By: ${project.owner || "Process Analyst"}
Date: ${today}

--------------------------------------------------
1. Executive Summary
--------------------------------------------------
This report summarizes the operational process analysis conducted using the
Vesimy Process Intelligence Platform.

The analysis includes value stream mapping, cycle time analysis, root cause
investigation and improvement identification.

--------------------------------------------------
2. Process Overview
--------------------------------------------------
Process Name: ${project.name}

Total Steps: ${project.steps.length}

--------------------------------------------------
3. Value Stream Analysis
--------------------------------------------------
${project.steps
  .map(
    (s: any, i: number) => `
Step ${i + 1}: ${s.name}
Cycle Time: ${s.cycleTime || "N/A"}
Queue Time: ${s.queue || "N/A"}
Operators: ${s.operators || "N/A"}
`
  )
  .join("\n")}

--------------------------------------------------
4. Root Cause Analysis
--------------------------------------------------
${project.rootCause || "Root cause analysis not completed."}

--------------------------------------------------
5. Waste Identification
--------------------------------------------------
${project.waste || "Waste analysis not completed."}

--------------------------------------------------
6. Improvement Opportunities
--------------------------------------------------
${project.improvements || "Improvement actions not defined."}

--------------------------------------------------
7. Standards Notice
--------------------------------------------------
This document structure aligns with recognized industrial
process analysis practices and references concepts from:

• ISO 9001 – Process approach and documented information
• ISO 22468 – Value Stream Management

This document supports operational analysis and
continuous improvement activities.
`
}