// TypeScript enabled
'use client'

export default function ReportFooter() {
  return (
    <div style={{
      marginTop: 40,
      paddingTop: 14,
      borderTop: '1px solid #DDD',
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      fontSize: 10,
      color: '#999',
      fontFamily: 'Arial, Helvetica, sans-serif',
    }}>
      <span>Generated by VeSiMy — Process Intelligence Platform · vesimy.com</span>
      <span>Confidential · {new Date().getFullYear()}</span>
    </div>
  )
}
